apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-ticket-service
  template:
    metadata:
      labels:
        app: ticket-ticket-service
    spec:
      containers:
      - name: ticket
        image: paulchhun/ticket-ticket-service:latest
        ports:
        - containerPort: 8000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-user-service
  template:
    metadata:
      labels:
        app: ticket-user-service
    spec:
      containers:
      - name: user
        image: paulchhun/ticket-user-service:latest
        ports:
        - containerPort: 8001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-comment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-comment-service
  template:
    metadata:
      labels:
        app: ticket-comment-service
    spec:
      containers:
      - name: comment
        image: paulchhun/ticket-comment-service:latest
        ports:
        - containerPort: 8002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-notification-service
  template:
    metadata:
      labels:
        app: ticket-notification-service
    spec:
      containers:
      - name: notification
        image: paulchhun/ticket-notification-service:latest
        ports:
        - containerPort: 8003