apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticketing-ingress
spec:
  rules:
  - host: ticketing.local
    http:
      paths:
      - path: /tickets
        pathType: Prefix
        backend:
          service:
            name: ticket-ticket-service
            port:
              number: 8000
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: ticket-user-service
            port:
              number: 8001
      - path: /comments
        pathType: Prefix
        backend:
          service:
            name: ticket-comment-service
            port:
              number: 8002
      - path: /notifications
        pathType: Prefix
        backend:
          service:
            name: ticket-notification-service
            port:
              number: 8003
