apiVersion: v1
kind: Service
metadata:
  name: ticket-ticket-service
spec:
  selector:
    app: ticket-ticket-service
  ports:
  - port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-user-service
spec:
  selector:
    app: ticket-user-service
  ports:
  - port: 8001
    targetPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-comment-service
spec:
  selector:
    app: ticket-comment-service
  ports:
  - port: 8002
    targetPort: 8002
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-notification-service
spec:
  selector:
    app: ticket-notification-service
  ports:
  - port: 8003
    targetPort: 8003
